### ISSUE TITLE
DMS lists hidden and unreadable files and directories.

### ISSUE THREAD

**Issue by Adirelle** [anacrolix/dms#44]
Firstly, I would like to thank you to for this simple, pure Go UPNP-AV server. It allows me to easily cross-compile it for a specific device which seems to have some quirks with Debian 9 and its usual tools. However, there are a couple of issues for my use case. I will try to tinker with them on my own. In the meantime, I will report them here. So, here is the first of them:

Right now, DMS lists all directories entries, including hidden ones (e.g. which name starts with a dot on Unix; may vary on other OSes) or otherwise unreadable per file permissions. Would it possible to ignore them ?

**Comment by anacrolix** [comment]
Thanks, this project seems to have new life and I haven't used it in years.

It's definitely possible to ignore dot files and inaccessible files. I believe they're not because one of the original design goals was not to hide things from the user, as other servers at the time required lots of parsing and nonsense up front.

I think flags modifying the dot file and unreadable file behaviour would seem appropriate, would they default to hidden or not?

Are you up to submitting PRs for this?

**Comment by Adirelle** [comment]
From what I understand from DMS's code it should not be too hard to implement. I will try to submit a PR. No ETA though, since I will do it on my sparse free time.
  
Edit: concerning the flags, I think they should be named "ignoreHidden" and "ignoreInaccessible" and be false by default, to avoid changing from the current behavior.

**Comment by anacrolix** [comment]
No problem, good luck!
