### ISSUE TITLE
Configurable notification interval

### ISSUE THREAD

**Issue by Adirelle** [anacrolix/dms#46]
Right now, DMS announces itself to the network every 5 seconds. This is a bit overkill, given than some devices "replies" to the announce by a Browse request. This could be a configurable value.

**Comment by anacrolix** [comment]
Yes definitely. I think the spec defaults to 30 or 60s or something. I sped this up because I found some OS and clients did not either listen, query or respond correctly. So for instance if you startup a player, it should search the network, rather than wait for the next announce from the server. It shouldn't be too hard to expose a flag.
